import { StyleSheet } from "react-native";

export const careTrendStyles = StyleSheet.create({
  card: {
    borderRadius: 20,
    padding: 18,
    gap: 14,
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  title: { flex: 1, color: "#0f172a", fontSize: 17, fontWeight: "700" },
  rangeControl: {
    flexDirection: "row",
    borderRadius: 12,
    padding: 3,
    backgroundColor: "rgba(15,23,42,0.07)",
  },
  rangeButton: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: 9,
    justifyContent: "center",
  },
  rangeButtonActive: { backgroundColor: "#0f172a" },
  rangeText: { color: "rgba(15,23,42,0.65)", fontSize: 11, fontWeight: "700" },
  rangeTextActive: { color: "white" },
  selectedSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
  },
  selectedDate: { color: "rgba(15,23,42,0.62)", fontSize: 12 },
  selectedValue: { color: "#0f172a", fontSize: 18, fontWeight: "800" },
  periodBounds: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  periodBoundText: {
    color: "rgba(15,23,42,0.68)",
    fontSize: 11,
    fontWeight: "700",
  },
  periodLine: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  periodRule: { flex: 1, height: 1, backgroundColor: "rgba(15,23,42,0.18)" },
  periodDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: "rgba(15,23,42,0.45)",
  },
  chart: {
    position: "relative",
    height: 92,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
  },
  chartBaseline: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: "rgba(15,23,42,0.2)",
  },
  slot: {
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  weekBoundary: {
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(15,23,42,0.18)",
  },
  barTrack: { flex: 1, width: "100%", justifyContent: "flex-end", alignItems: "center" },
  bar: {
    width: "72%",
    minWidth: 3,
    maxWidth: 22,
    borderRadius: 6,
    backgroundColor: "#60a5fa",
  },
  barEmpty: { backgroundColor: "rgba(15,23,42,0.1)" },
  barSelected: { backgroundColor: "#0f766e" },
  axis: {
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 16,
  },
  axisLabel: { color: "rgba(15,23,42,0.52)", fontSize: 9 },
  axisLabelSelected: { color: "#0f766e", fontWeight: "800" },
  insight: {
    minHeight: 42,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: "rgba(15,23,42,0.05)",
  },
  insightSignificant: { backgroundColor: "rgba(254,243,199,0.9)" },
  insightIcon: { color: "#0f172a" },
  insightText: { flex: 1, color: "#0f172a", fontSize: 12, fontWeight: "600" },
  empty: {
    minHeight: 118,
    borderRadius: 12,
    padding: 18,
    justifyContent: "center",
    backgroundColor: "rgba(15,23,42,0.04)",
  },
  emptyText: { color: "rgba(15,23,42,0.62)", textAlign: "center" },
});
