import { StyleSheet } from "react-native";
import { colors, radius } from "@/src/theme";

export const careTrendStyles = StyleSheet.create({
  card: {
    borderRadius: radius.card,
    padding: 18,
    gap: 14,
    backgroundColor: colors.surfaceRaised,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  title: { flex: 1, color: colors.text, fontSize: 17, fontWeight: "700" },
  rangeControl: {
    flexDirection: "row",
    borderRadius: radius.control,
    padding: 3,
    backgroundColor: colors.secondary,
  },
  rangeButton: {
    minHeight: 30,
    paddingHorizontal: 10,
    borderRadius: radius.input,
    justifyContent: "center",
  },
  rangeButtonActive: { backgroundColor: colors.primary },
  rangeText: { color: colors.textMuted, fontSize: 11, fontWeight: "700" },
  rangeTextActive: { color: colors.primaryText },
  selectedSummary: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
    gap: 12,
  },
  selectedDate: { color: colors.textSubtle, fontSize: 12 },
  selectedValue: { color: colors.text, fontSize: 18, fontWeight: "800" },
  periodBounds: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  periodBoundText: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  periodLine: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  periodRule: { flex: 1, height: 1, backgroundColor: colors.border },
  periodDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.textSubtle,
  },
  chart: {
    position: "relative",
    height: 92,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 3,
  },
  chartBaseline: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
  },
  slot: {
    flex: 1,
    height: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  weekBoundary: {
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: colors.border,
  },
  barTrack: { flex: 1, width: "100%", justifyContent: "flex-end", alignItems: "center" },
  bar: {
    width: "72%",
    minWidth: 3,
    maxWidth: 22,
    borderRadius: 6,
    backgroundColor: colors.textMuted,
  },
  barEmpty: { backgroundColor: colors.secondary },
  barSelected: { backgroundColor: colors.primary },
  axis: {
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 16,
  },
  axisLabel: { color: colors.textSubtle, fontSize: 9 },
  axisLabelSelected: { color: colors.text, fontWeight: "800" },
  insight: {
    minHeight: 42,
    borderRadius: radius.control,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: colors.surfaceMuted,
  },
  insightSignificant: { backgroundColor: colors.warningSurface },
  insightIcon: { color: colors.text },
  insightText: { flex: 1, color: colors.text, fontSize: 12, fontWeight: "600" },
  empty: {
    minHeight: 118,
    borderRadius: radius.control,
    padding: 18,
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
  },
  emptyText: { color: colors.textSubtle, textAlign: "center" },
});
