import { StyleSheet } from "react-native";
import { colors, radius } from "@/src/theme";

export const documentStyles = StyleSheet.create({
  section: { gap: 16 },
  formColumn: { gap: 12 },
  inlineRow: { flexDirection: "row", gap: 12 },
  inlineField: { flex: 1, minWidth: 0 },
  pickerButton: {
    minHeight: 46,
    borderRadius: radius.button,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.secondary,
  },
  pickerButtonDisabled: { opacity: 0.45 },
  pickerButtonText: { color: colors.secondaryText, fontWeight: "700" },
  pickerIcon: { color: colors.secondaryText },
  thumbnails: { gap: 10, paddingVertical: 2 },
  thumbnailWrapper: { width: 74, height: 74 },
  thumbnail: { width: 74, height: 74, borderRadius: radius.button, backgroundColor: colors.secondary },
  removePhoto: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: radius.pill,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.primary,
  },
  removePhotoIcon: { color: colors.primaryText },
  cardImage: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: radius.control,
    backgroundColor: colors.surfaceMuted,
  },
  previewImage: {
    width: "100%",
    aspectRatio: 4 / 5,
    borderRadius: radius.control,
    backgroundColor: colors.surfaceMuted,
  },
  previewThumbnails: { gap: 8, paddingVertical: 2 },
  previewThumbnail: { width: 58, height: 58, borderRadius: radius.button, backgroundColor: colors.secondary },
  previewThumbnailActive: { borderWidth: 2, borderColor: colors.primary },
});
