import { StyleSheet } from "react-native";

export const documentStyles = StyleSheet.create({
  section: { gap: 16 },
  formColumn: { gap: 12 },
  inlineRow: { flexDirection: "row", gap: 12 },
  inlineField: { flex: 1, minWidth: 0 },
  pickerButton: {
    minHeight: 46,
    borderRadius: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(15,23,42,0.08)",
  },
  pickerButtonDisabled: { opacity: 0.45 },
  pickerButtonText: { color: "#0f172a", fontWeight: "700" },
  pickerIcon: { color: "#0f172a" },
  thumbnails: { gap: 10, paddingVertical: 2 },
  thumbnailWrapper: { width: 74, height: 74 },
  thumbnail: { width: 74, height: 74, borderRadius: 10, backgroundColor: "#e2e8f0" },
  removePhoto: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15,23,42,0.8)",
  },
  removePhotoIcon: { color: "white" },
  cardImage: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.55)",
  },
  previewImage: {
    width: "100%",
    aspectRatio: 4 / 5,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
  },
  previewThumbnails: { gap: 8, paddingVertical: 2 },
  previewThumbnail: { width: 58, height: 58, borderRadius: 8, backgroundColor: "#e2e8f0" },
  previewThumbnailActive: { borderWidth: 2, borderColor: "#0f172a" },
});
